services:
  - type: web
    name: DocsConverter Pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    nativeEnvironment:
      packages:
        - pandoc
        - texlive-latex-recommended # Changed from texlive-latex-base
        - texlive-fonts-recommended
        - wkhtmltopdf
